implement client ping
tokio-rs/mini-redis pull request #108
Opened 2022-08-22 14:23 UTC by nomyfan

I found it was supported in server side.

2022-08-24 19:54 UTC, hds requested changes
A few small things to keep the code aligned with what was already there.

2022-08-24 19:54 UTC, hds commented on src/bin/cli.rs
> +        message: Option<String>,
Would it make sense to make this struct match the one in cmd and rename this field to `msg`?

2022-08-24 19:54 UTC, hds commented on src/client.rs
> +    /// # Examples
Missing empty line before the Example heading.

2022-08-24 19:54 UTC, hds commented on tests/client.rs
> +    let pong = client.ping(Some("你好世界".to_string())).await.unwrap();
nit: I would go with keeping each test case test one thing and split this test case into 2: one for an empty message and another for a non-empty message.

2022-08-25 00:58 UTC, nomyfan commented
Changes were made.

2022-08-25 08:51 UTC, hds approved these changes
Thanks!

2022-08-25 08:53 UTC, hds approved these changes

2022-08-25 09:10 UTC, Darksonn approved these changes

2022-08-25 09:10 UTC, merged